---
title: "Homogenous null model"
author: "Wiegand, Getzin, Hesselbarth"
output: 
  html_document:
    theme: cosmo
editor_options: 
  chunk_output_type: console
---

<br>

You can find a link to download the data [**here**](data.html). The `.zip`-folder includes two sub-folders, in which you can find the same datasets formatted for both *Programita* (filename extension `.dat`/`.mcf`) and *R* (filename extension `.txt`).

Especially when using *Programita*, but also using *R*, make screenshots of your results (or save the results to your disk in any other way) for the plenum discussion later.

For more information/background, please see *Homo_NullModels.pptx*.

### Exercise 1) 
Using the data set *DouglasFir_LiveDead_OGN*, calculate the O-ring statistic and the L-function. Here, pattern 1 gives the locations of living trees and pattern 2 gives the locations of dead trees. Comparing the univariate measures $O_{11}(r)$ and $L_{11}(r)$, how do they differ?

For more information, see Slides 6 ff., Slides 26 & Slides 51 ff.

### Exercise 2)
The L-function is said to have a memory effect because of its cumulative nature (counting points within discs instead of circles compared to the O-statistic). Can you see it in your results?

For more information, see Slides 26 & Slides 51 ff.

### Exercise 3 )
Redo the analysis but now with simulation envelopes and the null model CSR. How does the simulation envelope change, if you change the number of simulations from n = 39 to n = 199 (using the $5^{th}$ lowest/highest values).

For more information, see Slides 10 ff. & Slides 51 ff.

### Exercise 4 )
Also look at the O-ring statistic $O_{22}(r)$ and the L-function $L_{22}(r)$ for all dead trees. Is there a striking difference between dead and living Douglas fir trees? Again, use simulation envelopes and the null model CSR.

For more information, see Slides 10 ff. & Slides 51 ff.

```{r practical_1_plot_example, echo = FALSE, message = FALSE, fig.align = "center", fig.width = 5, fig.height = 5}
  library(ggplot2)
  library(spatstat)

  data <- read.table("Data/DouglasFir_LiveDead_OGN.txt", 
                     sep = ";", dec = ".", header = TRUE)
  
  window <- spatstat.geom::ripras(data[,1:2], shape = "rectangle")

  ggplot2::ggplot(data = data) + 
     ggplot2::geom_polygon(data = as.data.frame(window),
                           ggplot2::aes(x = x, y = y),
                           col = "black", fill = "grey85") +
    ggplot2::geom_point(ggplot2::aes(x = x, y = y, col = mark)) + 
    ggplot2::coord_equal() + 
    ggplot2::scale_color_viridis_c() + 
    ggplot2::guides(col = FALSE) + 
    ggplot2::theme_void()
```

...to be continued later today...
