---
title: "Cluster processes / Mark correlation function / Heterogenous conditions"
author: "Wiegand, Getzin, Hesselbarth"
output: 
  html_document:
    theme: cosmo
editor_options: 
  chunk_output_type: console
---

<br>

You can find a link to download the data [**here**](data.html). The `.zip`-folder includes two sub-folders, in which you can find the same datasets formatted for both *Programita* (filename extension `.dat`/`.mcf`) and *R* (filename extension `.txt`).

Especially when using *Programita*, but also using *R*, make screenshots of your results (or save the results to your disk in any other way) for the plenum discussion later.

For more information/background, please see *Homo_NullModels.pptx*.

# Cluster process
For more information, please see Slides 155 ff.

### Exercise 1)
Perform a point-pattern analysis on the *Hemlock_Adults_vs_SmallSaps* data set using CSR as null model. We are now especially interested in pattern 2, the small saplings. Using a cell size of 1 meter, calculate the $O_{22}(r)$. Up to which scale do we find significant clustering of the saplings?

### Exercise 2)
Use the pair-correlation function to fit a cluster process to the saplings data and use the fitted model to simulate null model data. Is the null model suitable for the field data?

### Exercise 3)
If the $O_{11}(r)$ function falls into the new envelope, you fitted good parameters for the cluster process. Have a look at the fitted parameters. Here, the typical cluster size and number of parents are  of interest.

### Exercise 4.)
Looking at the pattern of adult trees and saplings, is the fitted value for the number of parents realistic? If not so, what could be the reason?

# Mark correlation function (Stoyan's $k_{mm}$)

### Exercise 1)
The data set _Alive_DouglasFir_OGN_ contains the location and stem diameters (diameter at breast height, DBH) for all live Douglas fir trees in the Old-growth North plot. Calculate the mark-correlation function for the DBH. What do these results suggest?

### Exercise 2)
Calculate simulation envelopes to test for significance. As a null model use random labelleing. What could be a possible ecological explanation of your results?

# Inhomogeneous point patterns 

### Exercise 1) 
In the data set *Hemlock_Adults_vs_SmallSaps*, you can observe a clear gradient in the density of adult trees. Calculate $O_{11}(r)$ and $L_{11}(r)$ for pattern 1 (adult trees) to see up to which scale clustering of the trees can be observed using CSR as null model.

### Exercise 2)
Getzin et al. (2008) show that the study area is heterogenous. We are going to account for this heterogeneity by fitting a heterogeneous Poisson processes. Estimate $\lambda(x,y)$ and plot a map of the results. The gradient should be well visible.

### Exercise 3)
Use the previously estimated intensity $\lambda(x,y)$ to simulate a heterogenous Poisson process. Does $O_{11}(r)$ now fit into the simulation envelope? How do you interpret the result?

```{r practical_adv_plot_example, echo = FALSE, message = FALSE, fig.align = "center", fig.width = 10, fig.height = 5}
  library(ggplot2)
  library(patchwork)
  library(spatstat)

  # cluster/inhomo
  data <- read.table("Data/Hemlock_Adults_vs_SmallSaps.txt", 
                     sep = ";", dec = ".", header = TRUE)
  
  window <- spatstat.geom::ripras(data[,1:2], shape = "rectangle")

  ggplot_adults_vs_saps <- ggplot2::ggplot(data = data) +
    ggplot2::geom_polygon(data = as.data.frame(window),
                           ggplot2::aes(x = x, y = y),
                           col = "black", fill = "grey85") +
    ggplot2::geom_point(ggplot2::aes(x = x, y = y, col = mark)) + 
    ggplot2::coord_equal() + 
    ggplot2::scale_color_viridis_c() + 
    ggplot2::guides(col = FALSE) + 
    ggplot2::theme_void()
  
    # kmm(r)
    data <- read.table("Data/Alive_DouglasFir_OGN.txt", 
                     sep = ";", dec = ".", header = TRUE)
    
    window <- spatstat.geom::ripras(data[,1:2], shape = "rectangle")
    
    ggplot_alive_douglas <- ggplot2::ggplot(data = data) +
      ggplot2::geom_polygon(data = as.data.frame(window),
                           ggplot2::aes(x = x, y = y),
                           col = "black", fill = "grey85") +
    ggplot2::geom_point(ggplot2::aes(x = x, y = y, size = mark), shape = 1) + 
    ggplot2::coord_equal() + 
    # ggplot2::scale_color_viridis_c() + 
    ggplot2::guides(size = FALSE) + 
    ggplot2::theme_void()
    
    ggplot_adults_vs_saps + ggplot_alive_douglas
```

# Softcore- and Hardcore Process
### Exercise 1)
For this, use the data set *DouglasFir_LiveDead_OGN.dat* again. 

Can the small-scale regularity in the living Douglas fir trees be modeled by a hard-core process? What about a soft-core process?

#### Literature:

Getzin, S., Wiegand, T., Wiegand, K., He, F., 2008. Heterogeneity influences spatial patterns and demographics in forest stands. J. Ecol. 96, 807–820
